### PR TITLE
Fix Pytorch ABI incompatibilities

### PR DESCRIPTION
**Pull request by AntoinePrv**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] ~Reset the build number to `0` (if the version changed)~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] ~Ensured the license file is being packaged.~

This is a fix for https://github.com/conda-forge/pytorch_sparse-feedstock/issues/13 (`sparse` depends on `scatter` so I'm starting here).

The fix:
 - Removes `pytest`... from the runtime requirements as they are not needed at runtime
 - Pins Pytorch runtime version at the minor level to ensure ABI compatibility
 - Adds `pytorch` to the build matrix so that user can still pick their Pytorch version despite the version pinning

If this works properly, I will send similar PR for the other `pytorch_*` needed for `pytorch_geometric`.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
Do you really need to support two versions of pytorch. That seems like alot of work. 

It is also likely that we don't support all cuda versions on both versions.

It seems that the latest pytorch version works. 

Maybe we should have a pytorch pinning?

**Comment by hmaarrfk** [comment]
If you want to suggest adding `run_exports` to pytorch:

https://github.com/conda-forge/pytorch-cpu-feedstock/blob/master/recipe/meta.yaml#L22

We can probably patch the existing packages to add the missing `run_export`
https://github.com/conda-forge/conda-forge-repodata-patches-feedstock

Then add the pinning in:
https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml#L614

We would add a pinning of 1.8 for today, then when new builds arrive, we would use a migrator to increase the pytorch pinning for all packages that depend on pytorch 1.8.

**Comment by hmaarrfk** [comment]
It seems like there was already some work done on ensuring the pinning was good. Unfurtunately, the work needs to start in the feedstock, and that PR was never made.

**Comment by AntoinePrv** [comment]
So I looked a bit more in detail and for Pytorch 1.7, I think we would only need to add `cuda_compiler_version<11`.
Pytorch 1.8 seems to be always building fine (the only failing job is a timeout).

> If you want to suggest adding run_exports to pytorch

Thanks just did.

> We can probably patch the existing packages to add the missing `run_export`

Not quite sure what is going on there...

> Then add the pinning in:
> https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml#L614

This would set the Pytorch version for all recipes using Pytorch? Would that also pin recipes that only use Pytorch at runtime (i.e. through Python) and do not need such strict requirements?
I'm also not quite sure why Pytorch (and this recipe) are building for `cuda_compiler_version=11` if it is pinned to [`10.2`](https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/cfdac29ea9ffaae4723b15f2586306451a70c4a3/recipe/conda_build_config.yaml#L41)...

**Comment by AntoinePrv** [comment]
@conda-forge/pytorch_scatter what is the status here?

**Comment by oblute** [comment]
LGTM, thanks @AntoinePrv!

**Pull request merged**
