### PR TITLE
Rebuild for pytorch113

### PR DESCRIPTION
**Pull request by h-vetinari**
Migrator is stuck because pytorch 1.13 is only built for CUDA 11.2

### CODE REVIEW

**Comment by h-vetinari** [comment]
@conda-forge/pytorch_scatter, this is green, PTAL :)

**Review by Tobias-Fischer — APPROVED** [review]
Lgtm, thanks!

**Comment by h-vetinari** [comment]
Thanks @Tobias-Fischer! Looking at the recent GH activity of the other maintainers, I don't think we'll get another answer here, so could we go ahead and merge...? 🙃

**Comment by Tobias-Fischer** [comment]
Thanks @h-vetinari! Do you know if there are other similar packages that need to be migrated in this way?

**Comment by h-vetinari** [comment]
> Thanks @h-vetinari! Do you know if there are other similar packages that need to be migrated in this way?

Yes indeed. :)
See [here](https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/3826#issuecomment-1366612441)

**Pull request merged**
